### ISSUE TITLE
Monograph does not show attached files

### ISSUE THREAD

**Issue by jmcglone** [curationexperts/heliotrope#115]
Steps to reproduce

Using the UI: 

- [ ]  create a new monograph
- [ ] After creation, upload / attach files to the monograph
- [ ] View the updated monograph page

Expected Behavior:

Monograph show page is visible with associated metadata. Attached files are displayed below Monograph metadata.

Actual Behavior:

![screen shot 2016-03-23 at 4 20 03 pm](https://cloud.githubusercontent.com/assets/1686111/14000290/070999fc-f117-11e5-8c07-80e043093c72.png)

**Comment by val99erie** [comment]
This problem will only appear for monographs that have more than 10 attachments.

The problem is that the solr query by default returns only 10 rows.  The way I built up the set of solr documents, for all the documents beyond 10, the result will be nil.  So then on line 11 when we are trying to select the section docs, it's trying to operate on nil, which throws the nil error.

I'll fix it.
