### ISSUE TITLE
Add a press facet

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#126]
**ACCEPTANCE**
- [x] The platform-wide catalog page has a facet that lets me limit results to a single press.

**Comment by sethaj** [comment]
I can meet the AC by adding a line to controllers/catalog_controlller.rb:

`config.add_facet_field solr_name('press', :facetable), label: "Press", helper_method: :press_name_for_subdomain`

But it relies on a helper (in helpers/application_helpers.rb) to get Press.name from Press.subdomain since Press.name isn't in indexed in solr. A better idea would be to index Press.name is solr similar to Press.subdomain?

**Comment by sethaj** [comment]
Instead of using a helper to pull the press.name from the database to create the facet, press.name is now indexed in solr via monograph_indexer.rb

**Comment by sethaj** [comment]
This was PR 149
