### ISSUE TITLE
UI/CSS issues since CC upgrade

### ISSUE THREAD

**Issue by acozine** [curationexperts/heliotrope#136]
I'm putting all the UI oddities I notice into this ticket for now.

- [x] search box is small and hard to find with a mouse
- [ ] Monograph and Section show page have bullet points showing in the attributes list.  Get rid of them.
- [ ] ~~derivatives display in different sizes in the list of files attached to a monograph or section (this may be a feature rather than an issue, but it's definitely a change) - see screenshot:~~  moved to #182
![screen shot 2016-04-02 at 9 05 34 am](https://cloud.githubusercontent.com/assets/879121/14226797/56a2c1e4-f8b2-11e5-9f35-4ac886c212c8.png)

**Comment by val99erie** [comment]
There has been a lot of work on curation_concerns in the last week since we upgraded the version (including style work), so we should try upgrading again before we spend too much effort working on style fixes.

**Comment by acozine** [comment]
I'm still seeing different thumbnail sizes in the attached-files list after the curation concerns upgrade. Is this an issue for Michigan? If not, we can close this ticket. @shanitajohn - maybe you can call this out at Monday's standup.

**Comment by jmcglone** [comment]
If you add `list-unstyled` to the `ul` class in curation concerns' attribute renderer, the bullet points will go away on show pages. Specifically this line:

https://github.com/projecthydra-labs/curation_concerns/blob/master/app/renderers/curation_concerns/attribute_renderer.rb#L26

**Comment by jmcglone** [comment]
I guess my question is which is the best option -- a) override this in our app b) suggest it get fixed in cc c) wait until the next major release

**Comment by mark-dce** [comment]
Closing this ticket for now with the following strategy:
1) Track cc updates on a bi-weekly (per sprint) basis and determine when to incorporate them
2) See if any of the visual styling changes get fixed in cc over time
3) Schedule a review of the UI in July/August (presuming cc has stabilized some by then) and write up specific tickets for visual styling changes that need to be made and discuss on a case by case basis whether they should be made in cc or heliotrope
