### ISSUE TITLE
Add a data model for sub-brands

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#195]
**ACCEPTANCE**
- [x] A press can contain 0 or more sub-brands
- [x] A sub-brand may contain other sub-brands
- [x] A sub-brand and it's children may not contain itself (no loops)
- [x] A sub-brand has a title
- [x] A sub-brand has a description
- [x] A sub-brand can contain 0 or more monographs

**Comment by val99erie** [comment]
I added a follow-up story #224 to improve the UI on the monograph edit form.

I left the following things out-of-scope for this story because they are not needed for the summer beta release:
- Deleting a sub-brand (and updating all the sub-brand's monographs to remove the relationship)
- Faceting by sub-brand on the index page for the press_catalog_controller
- Adding a sub-brand to another sub-brand in the UI (e.g. Add a 'parent' field to the form for a sub-brand?)
