### ISSUE TITLE
Improve UI so that after adding a Title field in Describe your section, another row with another Add button doesn't appear

### ISSUE THREAD

**Issue by mbakeryo** [curationexperts/heliotrope#213]
When adding a section in the UI, after hitting the Add button, another row appears with another Add button, which makes it seem like you can add multiple sections at one time. (Important to note that the devs indicate that this behavior exists in other areas, too, not just the Add Section.)

Need to consider the UI and how to make it clear that only one section will be created.

**Comment by mbakeryo** [comment]
When adding multiple sections, it appears that only the last section added is actually created (or rather, attached to the monograph).

For example, in Winter in Michigan,  I added 4 sections: Introduction, Chapter 1: Trees, Chapter 2: More Trees, and Chapter 3: Even More Trees. Only the last chapter, Chapter 3: Even More Trees was created/attached to the monograph. 

I tried again by adding Introduction, Chapter 1: Trees, and Chapter 2: More Trees and only Chapter 2: More Trees was created/attached to the monograph.

Appears that even though the sections aren't being added to the monograph, the section was created, as Chapter 1: Trees is visible in the title drop-down (when adding a section).

**Comment by jmcglone** [comment]
What deployment is this on? Are the sections open access or private (by default they are private)? I'm having trouble re-creating this.

**Comment by mbakeryo** [comment]
This happens in both deployments.

The sections are set to private.

**Comment by mbakeryo** [comment]
Turns out that this isn't a bug. It was me not understanding what the "Add" next to the title field was supposed to do. I was seeing this as a way to add multiple sections to a monograph at one time and apparently there is no way to do this currently.

**Comment by mbakeryo** [comment]
Here is a screenshot of where the Add button should be removed:

<img width="629" alt="adding_a_section_remove_add" src="https://cloud.githubusercontent.com/assets/17436011/15355777/d24a7740-1cc2-11e6-93aa-d952cfe83d6d.png">

**Comment by jmcglone** [comment]
See related PR for hydra-editor [#113](https://github.com/projecthydra/hydra-editor/pull/113) 

@mbakeryo I met with Colin Fulton yesterday -- this was also a problem U-M UX dept uncovered while conducting user testing with UMRDR's sufia app. It was just fixed by U-M developers last week with an update to hydra-editor, which means it should be in the next curation concerns update. 

See https://github.com/projecthydra/sufia/issues/2021#issue-154744983 for a screenshot -- for all multi-value fields it makes it clear that you are adding a second title, creator, etc. on a single record.

As such, I'm going to close this.
