### ISSUE TITLE
Reordering files on File Manager page isn't working

### ISSUE THREAD

**Issue by val99erie** [curationexperts/heliotrope#83]
Steps to reproduce the problem:

1. Create a monograph and attach at least 2 files
2. On the show page for the monograph, click the File Manager button
3. On the file manager page, drag and drop the files to change the order.
4. Hit the "Save" button
5. Notice that nothing happens.  If you navigate away from the page and then come back, you can see that the files went back to their original order.  The new ordering wasn't saved.

**Comment by val99erie** [comment]
Note:  The "Save" button seems to start working if you reload the page.

**Comment by jcoyne** [comment]
That means it's probably an issue with turbolinks.  Usually this mean's the event in the javascript is bound to document ready rather than the page:load event that turbolinks emits. You can patch it to use Blacklight.onLoad instead. This handles all the events appropriately: https://github.com/projectblacklight/blacklight/blob/b11cf399a1416b995322032031f5543a5387cc8c/app/assets/javascripts/blacklight/core.js#L18-L24

**Comment by jcoyne** [comment]
Possibly this line here? https://github.com/projecthydra-labs/curation_concerns/commit/8f8441c1cb0cd16d7c4114ed2c4e892fd5c636f6#diff-6c4d11f05c97091ae1478247167d9b70R70

**Comment by jcoyne** [comment]
@tpendragon says to change it here: https://github.com/projecthydra-labs/curation_concerns/commit/8f8441c1cb0cd16d7c4114ed2c4e892fd5c636f6#diff-6c4d11f05c97091ae1478247167d9b70R8
